# Generated by Django 5.0.6 on 2024-07-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biomarker', models.CharField(default=None, max_length=100)),
                ('unit', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
