# Generated by Django 4.2.1 on 2023-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_doctor_patient_user_address_user_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.CharField(max_length=50, null=True)),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
