# Generated by Django 4.2.1 on 2023-05-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_medication"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="patient",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.patient"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="my_doctor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.doctor"
            ),
        ),
    ]
