# Generated by Django 4.2.1 on 2023-05-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_activity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("deadLine", models.DateTimeField(null=True)),
            ],
        ),
    ]
