# Generated by Django 4.2.1 on 2023-06-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Biomarkers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fbs", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                (
                    "hba1c",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                ("bmi", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "height",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                ("date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feetSituation", models.CharField(max_length=100, null=True)),
                ("FBS", models.IntegerField(null=True)),
                ("mood", models.CharField(max_length=50, null=True)),
                ("sleep", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("dateCreated", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
