# Generated by Django 4.2.1 on 2023-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_biomarkers_checkin_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("end_time", models.DateTimeField(null=True)),
                ("achievement", models.TextField(null=True)),
                ("image", models.ImageField(null=True, upload_to="")),
            ],
        ),
    ]
