# Generated by Django 4.2.1 on 2023-06-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_checkin_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="patient",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.patient"
            ),
        ),
    ]
