# Generated by Django 4.2.1 on 2023-06-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_cbt_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="role",
            field=models.CharField(
                choices=[("Patient", "Patient"), ("Sponsor", "Sponsor")],
                default="Patient",
                max_length=20,
            ),
        ),
    ]
