# Generated by Django 4.2.1 on 2023-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_patient_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="frequency",
            field=models.CharField(
                choices=[("once_a_day", "once a day"), ("twice_a_day", "twice a day")],
                max_length=50,
                null=True,
            ),
        ),
    ]
