# Generated by Django 4.2.1 on 2023-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_medication_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="patients",
            field=models.ManyToManyField(related_name="activities", to="api.patient"),
        ),
    ]
