# Generated by Django 4.2.1 on 2023-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_evaluation_activity_evaluation_badge_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="role",
            new_name="patientRole",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("doctor", "doctor"), ("Patient", "Patient")],
                default="Patient",
                max_length=10,
            ),
        ),
    ]
