# Generated by Django 4.2.1 on 2023-06-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_question_evaluation_questions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cbt",
            old_name="actions",
            new_name="behavior",
        ),
        migrations.RenameField(
            model_name="cbt",
            old_name="feelings",
            new_name="feeling",
        ),
        migrations.RenameField(
            model_name="cbt",
            old_name="thoughts",
            new_name="thought",
        ),
        migrations.RemoveField(
            model_name="checkin",
            name="sleep",
        ),
        migrations.RemoveField(
            model_name="evaluation",
            name="questions",
        ),
        migrations.AddField(
            model_name="cbt",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="checkin",
            name="sleepHours",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="FBS",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option1",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option2",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option3",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
