# Generated by Django 4.2.1 on 2023-06-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_rename_name_goal_goalname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="mood",
            field=models.CharField(
                choices=[
                    ("1", "I'm feeling great"),
                    ("2", "I'm feeling good"),
                    ("3", "I'm feeling ok"),
                    ("4", "I'm feeling bad"),
                    ("5", "I'm feeling Awful"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
