# Generated by Django 4.2.1 on 2023-06-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_checkin_mood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="mood",
            field=models.CharField(
                choices=[
                    ("1", "I'm feeling great"),
                    ("2", "I'm feeling good"),
                    ("3", "I'm feeling ok"),
                    ("4", "I'm feeling bad"),
                    ("5", "I'm feeling awful"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosisName",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("number", models.IntegerField(blank=True, null=True)),
                ("diagnosisDate", models.DateField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.patient",
                    ),
                ),
            ],
        ),
    ]
