# Generated by Django 4.2.1 on 2023-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_biomarkers_patient_alter_cbt_patient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groups",
            old_name="name",
            new_name="groupName",
        ),
        migrations.AddField(
            model_name="groups",
            name="patients",
            field=models.ManyToManyField(related_name="group", to="api.patient"),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="feetSituation",
            field=models.CharField(
                choices=[
                    ("cuts", "cuts"),
                    ("redness", "redness"),
                    ("swelling", "swelling"),
                    ("sores", "sores"),
                    ("blisters", "blisters"),
                    ("corns", "corns"),
                    ("calluses", "calluses"),
                    ("change_to_the_skin_or_nails", "change to the skin or nails"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
