# Generated by Django 4.2.1 on 2023-06-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_rename_name_groups_groupname_groups_patients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groups",
            name="patients",
            field=models.ManyToManyField(related_name="our_group", to="api.patient"),
        ),
    ]
