# Generated by Django 4.2.1 on 2023-08-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_groups_patients"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="doctor",
            managers=[],
        ),
    ]
