# Generated by Django 4.2.1 on 2023-08-05 14:51

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_alter_doctor_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="doctor",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
