# Generated by Django 4.2.1 on 2023-08-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_doctor_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Doctor"},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Doctor", "Doctor"), ("Patient", "Patient")],
                default="Patient",
                max_length=10,
            ),
        ),
    ]
