# Generated by Django 4.2.5 on 2023-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_doctor_options_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
