# Generated by Django 4.2.5 on 2023-09-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_correct_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='incorrect_answers',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
