# Generated by Django 4.2.5 on 2024-01-12 22:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='inAppLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=100)),
                ('order', models.TextField()),
                ('type', models.TextField()),
                ('title', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('data_title', models.CharField(default=None, max_length=255)),
                ('data_categories', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='journalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='scenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositiveCorrectionAlternative', models.CharField(default=None, max_length=100)),
                ('actionreply', models.TextField()),
                ('correction', models.TextField()),
                ('positiveActionReply', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shortBite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=100)),
                ('image', models.TextField()),
                ('title', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CBT_points', models.IntegerField(default=0)),
                ('answer_1', models.CharField(default=None, max_length=100)),
                ('answer_2', models.CharField(default=None, max_length=100)),
                ('answer_3', models.TextField()),
                ('correct_answer', models.IntegerField(default=0)),
                ('description', models.CharField(default=None, max_length=100)),
                ('explanation', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=100)),
                ('question', models.CharField(default=None, max_length=100)),
                ('learning_points', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('topic', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(default=None, max_length=100)),
                ('uid', models.CharField(default=None, max_length=100)),
                ('display_name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='psychomarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('depression', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('topic', models.CharField(default=None, max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='feelings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anger', models.BooleanField(default=False)),
                ('fear', models.BooleanField(default=False)),
                ('happiness', models.BooleanField(default=False)),
                ('joy', models.BooleanField(default=False)),
                ('love', models.BooleanField(default=False)),
                ('sadness', models.BooleanField(default=False)),
                ('shame', models.BooleanField(default=False)),
                ('strength', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(default=None, max_length=100)),
                ('assessmentQuestion', models.CharField(default=None, max_length=100)),
                ('badges', models.TextField(default=None)),
                ('biomarkers', models.TextField(default=None)),
                ('bites', models.TextField(default=None)),
                ('categories', models.CharField(default=None, max_length=100)),
                ('feelings', models.CharField(default=None, max_length=100)),
                ('inAppLinks', models.CharField(default=None, max_length=100)),
                ('inquiry', models.CharField(default=None, max_length=100)),
                ('items', models.CharField(default=None, max_length=100)),
                ('journal', models.CharField(default=None, max_length=100)),
                ('journalPrompt', models.CharField(default=None, max_length=100)),
                ('majorAssessment', models.CharField(default=None, max_length=100)),
                ('psychomarkers', models.CharField(default=None, max_length=100)),
                ('scenarios', models.CharField(default=None, max_length=100)),
                ('trivia', models.CharField(default=None, max_length=100)),
                ('users', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
                ('tags', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.tags')),
            ],
        ),
        migrations.CreateModel(
            name='bites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('tags', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.tags')),
            ],
        ),
        migrations.CreateModel(
            name='biomarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodGlucose', models.IntegerField(default=0)),
                ('bloodGlucoseType', models.CharField(default=None, max_length=100)),
                ('dailyActivity', models.IntegerField(default=0)),
                ('dailyCarbs', models.IntegerField(default=0)),
                ('weeklyActivity', models.IntegerField(default=0)),
                ('sleepQuality', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('FBS', models.IntegerField(default=0)),
                ('HBA1c', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarkers_frontend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=django.utils.timezone.now, max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('tags', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.tags')),
            ],
        ),
    ]
