# Generated by Django 4.2.5 on 2024-01-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='data_categories',
        ),
        migrations.RemoveField(
            model_name='items',
            name='data_title',
        ),
        migrations.AddField(
            model_name='items',
            name='data',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.item'),
        ),
    ]
