# Generated by Django 4.2.5 on 2023-11-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_document_field_bites_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bites',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document'),
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
