# Generated by Django 4.2.5 on 2023-11-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_bites_document_delete_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=100)),
                ('badges', models.TextField()),
                ('biomarkers', models.TextField()),
                ('bites', models.TextField()),
                ('categories', models.CharField(max_length=100)),
                ('feelings', models.CharField(max_length=100)),
                ('inquiry', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('journalPrompt', models.CharField(max_length=100)),
                ('scenarios', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('users', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='biomarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_glucose', models.IntegerField()),
                ('FBS', models.IntegerField()),
                ('HBA1c', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sleepQuality', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_points', models.IntegerField()),
                ('CBT_points', models.IntegerField()),
                ('Learning_points', models.IntegerField()),
                ('Social_points', models.IntegerField()),
                ('language', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('time', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
    ]
