# Generated by Django 5.0.6 on 2024-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarkers',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
