# Generated by Django 4.2.5 on 2024-01-10 14:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0004_collection_biomarkers_badges_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='activities',
            name='Activity_points',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='CBT_points',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='Learning_points',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='Social_points',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='language',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='location',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='time',
        ),
        migrations.RemoveField(
            model_name='biomarkers',
            name='Blood_glucose',
        ),
        migrations.RemoveField(
            model_name='biomarkers',
            name='height',
        ),
        migrations.AddField(
            model_name='activities',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AddField(
            model_name='activities',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biomarkers',
            name='bloodGlucose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biomarkers',
            name='bloodGlucoseType',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='biomarkers',
            name='dailyActivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biomarkers',
            name='dailyCarbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biomarkers',
            name='weeklyActivity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='assessmentQuestion',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='inAppLinks',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='journal',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='majorAssessment',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='psychomarkers',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='collection',
            name='trivia',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='biomarkers',
            name='FBS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biomarkers',
            name='HBA1c',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biomarkers',
            name='sleepQuality',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biomarkers',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='biomarkers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarkers_frontend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biomarkers',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='activities',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='badges',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='biomarkers',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='bites',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='collection',
            name='categories',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='feelings',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='inquiry',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='item',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='journalPrompt',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='scenarios',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='users',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(default=None, max_length=100)),
                ('uid', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_2', models.CharField(default=None, max_length=100)),
                ('answer_3', models.TextField()),
                ('CBT_points', models.IntegerField(default=0)),
                ('correct_answer', models.IntegerField(default=0)),
                ('answer_1', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=100)),
                ('explanation', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=100)),
                ('question', models.CharField(default=None, max_length=100)),
                ('learning_points', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('topic', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=100)),
                ('image', models.TextField()),
                ('title', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='scenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositiveCorrectionAlternative', models.CharField(default=None, max_length=100)),
                ('actionreply', models.TextField()),
                ('correction', models.TextField()),
                ('positiveActionReply', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='psychomarkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('depression', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='majorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('name', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('topic', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='inAppLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=100)),
                ('order', models.TextField()),
                ('type', models.TextField()),
                ('title', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='feelings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anger', models.BooleanField(default=False)),
                ('fear', models.BooleanField(default=False)),
                ('happiness', models.BooleanField(default=False)),
                ('joy', models.BooleanField(default=False)),
                ('love', models.BooleanField(default=False)),
                ('sadness', models.BooleanField(default=False)),
                ('shame', models.BooleanField(default=False)),
                ('strength', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.CreateModel(
            name='assessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorAssessment', models.CharField(max_length=100)),
                ('max', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('question', models.CharField(default=None, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.document')),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.tags'),
        ),
        migrations.AlterField(
            model_name='bites',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.tags'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.tags'),
        ),
    ]
