# Generated by Django 5.0.6 on 2024-07-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_biomarkers_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='selfAwarenessScenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction1from0to2', models.TextField()),
                ('correction2from3to5', models.TextField()),
                ('interactiveStatement', models.TextField()),
                ('recommendation1', models.TextField()),
                ('recommendation2', models.TextField()),
                ('scenarioID', models.CharField(default=None, max_length=100)),
                ('story', models.TextField()),
                ('storyTitle', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=100)),
                ('majorAssessment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.majorassessment')),
            ],
        ),
    ]
