# Generated by Django 5.0.6 on 2024-07-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_alter_biomarkers_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='weight',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
